- Q: "Pyro4.errors.CommunicationError: cannot connect to (u'192.168.178.12', 41544): [Errno 111] Connection refused"
  => You need to start the roslaunch2_server instance on the remote host first.
